### ISSUE TITLE
Page not found (404) in the Django project.

### ISSUE THREAD

**Issue by jai-tom** [iam-veeramalla/Docker-Zero-to-Hero#23]
After containerisation when accessing the website using given port address error message shows as follows:

==================================

"Using the URLconf defined in devops.urls, Django tried these URL patterns, in this order:

demo/
admin/
The empty path didn’t match any of these.

You’re seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page."

**Comment by HemanthGangula** [comment]
I've encountered a similar issue before. 
Ensure the URL is in the following format: http://<ec2 instance public IP>:8000/demo/, 
like this: http://10.0.1.2:8000/demo/. Make sure to replace <ec2 instance public IP> with the actual public IP address of your EC2 instance. 
Also, make sure you have enabled port 8000 in the inbound rules of your EC2 instance's security group. This should resolve the problem.

**Comment by MayuDPatil** [comment]
I have enabled 8000 in inbound rule but still not able to load the site getting error 

Not Found: /
[17/Nov/2024 05:19:22] "GET / HTTP/1.1" 404 2309

**Comment by ashask2781** [comment]
I am running it in my local in docker desktop and even I am not able to open the webpage. not sure if I am missing something

**Comment by Anj03-hub** [comment]
Page not found (404)
Request Method:	GET
Request URL:	http://54.173.215.61:8000/
Using the URLconf defined in devops.urls, Django tried these URL patterns, in this order:

demo/
admin/
The empty path didn’t match any of these.

You’re seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

I am getting this error , i have enabled port 8000 for my ec2 instance

**Comment by Anj03-hub** [comment]
> Page not found (404) Request Method: GET Request URL: http://54.173.215.61:8000/ Using the URLconf defined in devops.urls, Django tried these URL patterns, in this order:
> 
> demo/ admin/ The empty path didn’t match any of these.
> 
> You’re seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
> 
> I am getting this error , i have enabled port 8000 for my ec2 instance

I was able to load thw web application after using the command as <ec2instanceip>:8000/demo

**Comment by Anj03-hub** [comment]
> Page not found (404) Request Method: GET Request URL: http://54.173.215.61:8000/ Using the URLconf defined in devops.urls, Django tried these URL patterns, in this order:
> 
> demo/ admin/ The empty path didn’t match any of these.
> 
> You’re seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
> 
> I am getting this error , i have enabled port 8000 for my ec2 instance

I was able to load the web page after using the URL as https://<ec2instanceip>:8000/demo
